### ISSUE TITLE
getAccountAddress() broken - could be dependency issue

### ISSUE THREAD

**Issue by sisyphusSmiling** [onflow/flow-js-testing#182] opened 2022-09-09 22:34 UTC
### Problem

Running `getAccountAddress()` results in error. Because this may be a dependency issue, I will also make an issue in [`flow-cadut`](https://github.com/onflow/flow-cadut)

### Steps to Reproduce

 As an example, running the following in a test using `flow-js-testing`:

```
test("getAccountAddress breaks", async () => {
        const testAddress = await getAccountAddress("TestAddress");
    });
```

Gets us the following output:

```
Cannot read properties of undefined (reading 'replace')
TypeError: Cannot read properties of undefined (reading 'replace')
    at Object.replace [as replaceImportAddresses] (/Users/gsanchez/Workspace/flow-core-contracts/lib/js/test/node_modules/@onflow/flow-cadut/src/imports.js:103:15)
    at replaceImportAddresses (/Users/gsanchez/Workspace/flow-core-contracts/lib/js/test/node_modules/@onflow/flow-js-testing/src/interaction.js:95:14)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Alternatively, this can be reproduced with an existing repo - [`flow-nft`'s JS tests](https://github.com/onflow/flow-nft) are no longer passing. Try pulling and running those and you should get something like the output quoted above.

### Acceptance Criteria

`getAccountAddress()` runs without error

### Context

Currently blocked from writing tests for the [Execution Node versioning contract](https://github.com/onflow/flow-core-contracts/issues/308)

**Comment by adbario** [comment] 2022-09-14 01:03
Having the same issue here as @sisyphusSmiling. Downgraded to `0.3.0-alpha.14` for now to get things rolling again while waiting for a fix.

**Comment by adbario** [comment] 2022-09-14 23:34
@gregsantos This is what I get with `0.3.0-alpha.15` on the following test:

```javascript
it("should get the test account address", async () => {
  await getAccountAddress("TestAddress");
});
```

```
      at _callee$ (node_modules/@onflow/util-logger/src/util-logger.js:44:7)
      at tryCatch (node_modules/@babel/runtime/helpers/regeneratorRuntime.js:86:17)
      at Generator._invoke (node_modules/@babel/runtime/helpers/regeneratorRuntime.js:66:24)
      at Generator.next (node_modules/@babel/runtime/helpers/regeneratorRuntime.js:117:21)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at _next (node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)

 FAIL  tests/hello-world.test.ts
  HelloWorld
    ✕ should get the test account address (636 ms)

  ● HelloWorld › should get the test account address

    TypeError: Cannot read properties of undefined (reading 'replace')

      31 |
      32 |   it("should get the test account address", async () => {
    > 33 |     const testAddress = await getAccountAddress("TestAddress");
         |                         ^
      34 |   });
      35 | });
      36 |

      at Object.replace [as replaceImportAddresses] (node_modules/@onflow/flow-js-testing/node_modules/@onflow/flow-cadut/src/imports.js:103:15)
      at replaceImportAddresses (node_modules/@onflow/flow-js-testing/src/interaction.js:95:14)
      at Object.<anonymous> (tests/hello-world.test.ts:33:25)
```

**Comment by adbario** [comment] 2022-09-15 09:24
> Also I'm able to successfully run all tests from **[flow-nft](https://github.com/onflow/flow-nft/tree/master/lib/js/test)**

Please note that the tests on **[flow-nft](https://github.com/onflow/flow-nft/tree/master/lib/js/test)** use `0.3.0-alpha.14` which works fine for me as well. The issues reported are for the latest version `0.3.0-alpha.15`.

To double check this, I upgraded the testing library on flow-nft and all the same errors come up.

**Comment by adbario** [comment] 2022-09-15 09:25
> Also I'm able to successfully run all tests from **[flow-nft](https://github.com/onflow/flow-nft/tree/master/lib/js/test)**

@gregsantos Please note that the tests on **[flow-nft](https://github.com/onflow/flow-nft/tree/master/lib/js/test)** use `0.3.0-alpha.14` which works fine for me as well. The issues reported are for the latest version `0.3.0-alpha.15`

To double check this, I upgraded the testing library on flow-nft and all the same errors come up.

**Comment by bluesign** [comment] 2022-09-15 11:09
@gregsantos 

This is a strange issue ( though was fun to debug), I don't know javascript much. ( so my analysis can be wrong ) 

Problem is here:

https://github.com/onflow/flow-js-testing/blob/457886be649852e60aafd33e695ff66719c18e01/src/interaction.js#L123

```javascript
export const sendTransaction = async (...props) => {
  let result = null,
    err = null
  const logs = await captureLogs(async () => {
    try {
      const extractor = extractParameters("tx")
      const {code, args, signers, limit} = await extractor(props)

      const serviceAuth = authorization()
```

here somehow `props` having problem passing sometimes ( or somehow overwritten ) 

changing something like: 

```javascript
export const sendTransaction = async (...props) => {
  let result = null,
    err = null
 let propsOuter = props
  const logs = await captureLogs(async () => {
    try {
      const extractor = extractParameters("tx")
      const {code, args, signers, limit} = await extractor(propsOuter)

      const serviceAuth = authorization()
```
solves the problem.

**Comment by jribbink** [comment] 2022-09-15 15:37
@bluesign is correct and this is yet another one of these strange microbundle issues related to async function arguments, very similar to previous occurances in @onflow/fcl.  The bundled code looks like the following:

```javascript
const sendTransaction = function () {
  try {
    let result = null,
        err = null;
    return Promise.resolve(captureLogs(function () {
      try {
        const _arguments = arguments;

        const _temp7 = _catch(function () {
          const extractor = extractParameters$1("tx");
          return Promise.resolve(extractor([].slice.call(_arguments))).then(function ({
            code,
            args,
            signers,
            limit
          }) {
```

Note that the arguments come from the inner function `captureLogs` and not the outer function `sendTransaction` as intended.

Using the internal build tool, @onflow/fcl-bundle, is not possible without a large amount of refactoring (see #152) because flow-js-testing has a lot of tricky circular dependencies.  Microbundle is somehow able to ignore these, but fcl-bundle is not (my guess is something related to the use of the rollup babel plugin in fcl-bundle and this confuses the code transformations somehow).

**Comment by adbario** [comment] 2022-09-18 11:01
> Maybe some JS bug, packer bug, or something else. If someone knows the answer I am curious too

Javascript just never stops surprising us.

And yes, all the tests within the example folder are passing. But when the library is bundled that doesn't seem to be the case anymore.

**Comment by justinbarry** [comment] 2022-09-19 18:48
@jribbink Good call on the scoping issue. Was able to patch it in this case.

**Comment by sisyphusSmiling** [comment] 2022-10-21 17:06
Looks like this issue could be popping up again in #191. Cross posting here for visibility

**Comment by jribbink** [comment] 2022-10-21 22:24
Merging PR #190 should fix this.  Account addresses are stored on chain and since `executeScript` should effectively be broken, it would go to reason that `getAccountAddress` is also broken.

**Comment by gregsantos** [comment] 2022-10-24 23:59
Fixed via https://github.com/onflow/flow-js-testing/pull/190

**Closed by gregsantos** 2022-10-24 23:59 UTC
Labels: bug
