### ISSUE TITLE
Randomly failing tests

### ISSUE THREAD

**Issue by MaxStalker** [onflow/flow-js-testing#61] opened 2021-11-26 15:03 UTC
### Problem
Running multiple test files would result in random tests failing to complete properly.
When tests are defined in a single file - they run as expected.

### Discovery
Most of the time it doesn't happen, when tests would be run locally. Though some community members with fast computers reported the same issues in local environment.

Apparently, the culprit of the problem is `config` method from `@onflow/fcl` package, which creates context, when `@onflow/fcl` package is loaded. Since it's a singleton, all test files would share the same context and independently change it, closing emulator and changing port values in the process.

Setting `--runInBand` flag on Jest doesn't make any effect - random tests still would occur.

### Potential Solutions
- Create custom Jest test runner, which would collect all available files into a single file, before running it
- Create a FCL-level solution, which would allow to define contexts to execute network interactions

### Context
This issue is related to #47

**Comment by MaxStalker** [comment] 2021-12-10 14:48
One of the stable solutions was using serial-runner. Specifically "@codejedi365/jest-serial-runner" (original one have an issue, which is not resolved at the time of writing - https://github.com/gabrieli/jest-serial-runner/issues/16)

We will update default config to include this changes. Existing projects can use updated jest config:
```js
module.exports = {
	testEnvironment: "node",
	verbose: true,
	coveragePathIgnorePatterns: ["/node_modules/"],
	setupFiles: ["<rootDir>/test/setup.js"],
	projects: [
		{
			displayName: "Cadence Tests",
			testMatch: ["<rootDir>/test/*.test.js"],
			runner: "@codejedi365/jest-serial-runner",
		},
	],
};
```
You will need to install `jest-serial-runner` via:
```sh
npm install @codejedi365/jest-serial-runner
```
or
```sh
yarn add @codejedi365/jest-serial-runner
```

**Comment by kerrywei** [comment] 2021-12-10 16:59
A [PR](https://github.com/onflow/kitty-items/pull/150) is made in KittyItem to pilot launch this serial test runner, however, PR is blocked.

**Comment by MaxStalker** [comment] 2021-12-17 15:43
### Follow up for `jest-serial-runner` solution
It doesn't work perfectly every time. It is increased overall percentage of successful tests, but we still see randomly failing tests in CI.

### Next Steps
- [ ] ensure this is not a port issue and run emulator on new port every time
- [ ] enable emulator logging and see maybe it's reporting issues, before crashing
- [ ] wrap `emulator.start` calls with promises to wait for emulator to start and stop properly

**Comment by kerrywei** [comment] 2022-01-12 19:55
I merged in https://github.com/onflow/flow-js-testing/pull/73 which should permanently address failures caused by js testing library prematurely flags the readiness of the emulator. 
the latest version is 0.2.2-alpha.3

**Closed by kerrywei** 2022-01-12 19:55 UTC
Labels: bug, Developer Tool Team
